### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by shanchanggo** [SynodicMonth/NodeGraphic#1]
Hi !friends， could you have time to note it ? 
I wait it !

**Comment by SynodicMonth** [comment]
do you mean documention? There's a bried documention in 实验报告.pdf.

**Comment by shanchanggo** [comment]
I am a fresher! I need note the code everyline  !  by the way , I look forward your new project .

**Comment by shanchanggo** [comment]
hello! dear friend ,      do you have time to note detailly!

**Comment by shanchanggo** [comment]
Hi friends, 你大几了？

**Comment by SynodicMonth** [comment]
I'm not planning to add detiled note for every functions, but if u need any specific ones i can add a brief one. If u have any questions, just ask me freely.
